apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-file-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-file-store
  template:
    metadata:
      labels:
        app: simple-file-store
    spec:
      containers:
      - name: simple-file-store
        image: sauravschandra/simple_file_store:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-file-store-service
spec:
  selector:
    app: simple-file-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
